### PR TITLE
Feature/hf dataset augmentation

### LINKED ISSUE #621: Add support for HF datasets augmentations

### PR DESCRIPTION
**Pull request by RakshitKhajuria**
# Description

Added support for loading HuggingFace Datasets for Augmentation tasks.

Notebook  ➤ [Demo](https://github.com/JohnSnowLabs/langtest/blob/feature/hf-dataset-augmentation/demo/tutorials/misc/Augmentation_Control_Notebook.ipynb)
-------------------------------------------------------------------------------------------------
➤ Fixes #621 

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Usage

```
custom_proportions = {
    'add_ocr_typo':0.3
}

data_kwargs = {
      "data_source" : "glue",
      "subset": "sst2",
      "feature_column": "sentence",
      "target_column": "label",
      "split": "train"
       }
harness.augment(
    training_data = data_kwargs,
    augmented_data ="augmented_glue.csv",
    custom_proportions=custom_proportions,
    export_mode="add",
)
```
## Checklist:

- [x] I've added Google style docstrings to my code.
- [x] I have linted my code
- [x] I have added tests to cover my changes.

## Screenshots (if appropriate):

### CODE REVIEW

**Review by JulesBelveze — COMMENTED** [review]
@Prikshit7766 Why not doing something like?
```
harness.augment(
    input_path="glue",
    output_path="augmented.csv",
    custom_proportions=custom_proportions,
    export_mode="transformed",
    data_kwargs={
        "subset": "sst2",
        "feature_column": "sentence",
        "target_column": "label",
        "split": "train"
    }
)
```
then you simply have to do:
```
self.df.load_data(**data_kwargs)
```

**Comment by RakshitKhajuria** [comment]
> @Prikshit7766 Why not doing something like?
> 
> ```
> harness.augment(
>     input_path="glue",
>     output_path="augmented.csv",
>     custom_proportions=custom_proportions,
>     export_mode="transformed",
>     data_kwargs={
>         "subset": "sst2",
>         "feature_column": "sentence",
>         "target_column": "label",
>         "split": "train"
>     }
> )
> ```
> 
> then you simply have to do:
> 
> ```
> self.df.load_data(**data_kwargs)
> ```
Do we have to change this for the loading of hf dataset in the harness as well?
If yes then we will be adding one more parameter to the haness class. @JulesBelveze

**Comment by Prikshit7766** [comment]
we do in this way 
```
harness.augment(
    input_path="glue",
    output_path="augmented.csv",
    custom_proportions=custom_proportions,
    export_mode="transformed",
    data_kwargs={
        "subset": "sst2",
        "feature_column": "sentence",
        "target_column": "label",
        "split": "train"
    }
)
```
 
but instead of   `self.df.load_data(**data_kwargs)`    we can do like 
```            data = self.df.load_data(
                feature_column=data_kwargs.get("feature_column", "text"),
                target_column=data_kwargs.get("target_column", "label"),
                split=data_kwargs.get("split", "test"),
                subset=data_kwargs.get("subset", None),
            )
```
in this way we don't need to modify the  `load_data` method of `HuggingFaceDataset`
because we are using this `load_data` while loading  hf dataset

**Comment by JulesBelveze** [comment]
@RakshitKhajuria Yes I don't think it's too bad to have an optional parameter called `data_kwargs` in the `Harness` constructor..

**Comment by ArshaanNazir** [comment]
> @RakshitKhajuria Yes I don't think it's too bad to have an optional parameter called `data_kwargs` in the `Harness` constructor.. Also, I don't see any other way around it.. @ArshaanNazir what's your opinion?

@JulesBelveze adding an additional param was the initial thought. However David insisted of not adding more params to harness class.

**Comment by JulesBelveze** [comment]
@ArshaanNazir then I guess the only way is to delete the `input_path` parameter and have a `data_kwargs` parameter of type Dict which requires a key `input_path` and other keys are optional?

**Comment by ArshaanNazir** [comment]
> `data_kwargs`

In this case, we have name it as training_data (parameter as Dict) , with data_source and other optional and output_path can be augmented_data

**Comment by Prikshit7766** [comment]
> > `data_kwargs`
> 
> In this case, we can name it as training_data (parameter as Dict) , with data_source and other optional and output_path can be augmented_data

@ArshaanNazir 
can you provied one  sample  example for  both the cases

**Review by JulesBelveze — APPROVED** [review]
LGTM

**Comment by RakshitKhajuria** [comment]
> LGTM

@JulesBelveze don't merge it yet. We will be updating this PR with the notebook 😊

**Pull request merged**
